# Assignment week - 1 of Applied Data Science 

# Submitted by - Rahul Kumar                    ,  Registration number - 20BEC1186

# Mail ID - rahulkumar2020a@vitstudent.ac.in

# Question 1:

In [1]:
def disp(name , age):
    print("My Name is :", name)
    print("My Age is :", age)

In [2]:
name = input()
age = int(input())

Rahul Kumar
23


In [3]:
disp(name ,age)

My Name is : Rahul Kumar
My Age is : 23


# Question 2:

In [4]:
x = "Datascience is used to extract meaningful insights."
li = []
li = x.split(" ")
li

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

# Question 3:

In [5]:
def multi(a,b):
    print(a*b)

n = int(input())
m = int(input())
multi(n,m)

23
89
2047


# Question 4:

In [15]:
st_cp = {'chennai':'Tamil Nadu', 'Lucknow':'Uttar Pradesh', 'Mumbai': 'Maharashtra','Jaipur':'Rajasthan', 'patna':'Bihar'}
for i in st_cp:
    print("The Capital of State (value):",st_cp[i] +" is (key) :" ,i )

The Capital of State (value): Tamil Nadu is (key) : chennai
The Capital of State (value): Uttar Pradesh is (key) : Lucknow
The Capital of State (value): Maharashtra is (key) : Mumbai
The Capital of State (value): Rajasthan is (key) : Jaipur
The Capital of State (value): Bihar is (key) : patna


# Question 5:

In [23]:
range_1 = range(2, 2002, 2)
list_1 = list(range_1)
print(list_1)
print("\n\n",len(list_1))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420, 42

# Question 6: 

In [33]:
import numpy as np
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
arr.ndim

2

In [36]:
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if(j==i):
            arr[i][j] = 1
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Question 7:

In [42]:
import numpy as np
matrix_arr = np.arange(1,10).reshape(3,3)

In [43]:
print(matrix_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Question 8:

In [46]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
print("Matrix a = \n",a)
print("\n Matrix b = \n",b)

Matrix a = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Matrix b = 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [48]:
c = a+b
print("The addition of the two matrix a and b \n c = \n",c)

The addition of the two matrix a and b 
 c = 
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


# Question 9:

In [58]:
from datetime import date, timedelta

sdate = date(2023,2,1)   # start date
edate = date(2023,3,2)   # end date


In [63]:
import pandas as pd
pd.date_range(sdate,edate-timedelta(days=1),freq='d')

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')

# Question 10:

In [60]:
import pandas as pd
dic = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
data = pd.DataFrame(dic)
data

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240

In [62]:
data.iloc[: , :]

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240